/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.gradle.dep.mgr.app;

import test.gradle.dep.mgr.list.LinkedList;

import static test.gradle.dep.mgr.utilities.StringUtils.join;
import static test.gradle.dep.mgr.utilities.StringUtils.split;
import static test.gradle.dep.mgr.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
