/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.gradle.template.app;

import simple.gradle.template.list.LinkedList;

import static simple.gradle.template.utilities.StringUtils.join;
import static simple.gradle.template.utilities.StringUtils.split;
import static simple.gradle.template.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
